### ISSUE TITLE
Crash at runtime

### ISSUE THREAD

**Issue by gaetandezeiraud** [Wumpf/nvidia-dxr-tutorial#1]
Hi, 
I have follow the Nvidia's DX12 raytracing tutorial. 
And I get an error at `HRESULT hr = m_device->CreateStateObject(&pipelineDesc, IID_PPV_ARGS(&rtStateObject));`  with `E_INVALIDARG One or more arguments are invalid.`. Even the official source code don't work with the last version of Windows. Same problem. Any idea?

Thanks!

**Comment by Wumpf** [comment]
Hi @Brouilles! I haven't touched this stuff in ages, but I gave it a quick shot with a fresh clone just now and it works just fine for me.
I ran it with Windows 10.0.19041, a Nvidia GTX 1070Ti, driver version 452.06. Worth noting that my VS2019 didn't have the right Windows sdk for the project, so I let it update to whatever it had installed - don't think that adds another source of error but who knows.
Maybe this api call fails if DXR is not available on your machine? Better double check your driver and windows problem.
Had plenty of issues back then with the original source, thus the fork you see here.

**Comment by gaetandezeiraud** [comment]
Hi! 
Thanks for your message! So, after long days with the problem. I have found a solution. It's seems to be a bug or a breaking change modification in the last Windows SDK. So,  it’s working with the Windows SDK 10.0.18362.0. But not with the 10.0.19041.0.

Thanks alot for your answer and time!
